# Generated by Django 4.1.7 on 2023-02-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "username",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=50)),
                ("referral_code", models.CharField(max_length=50)),
                ("referral_count", models.IntegerField()),
            ],
        ),
    ]
