# Generated by Django 4.1.7 on 2023-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="theAlly",
            fields=[
                (
                    "username",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(default="", max_length=50)),
                ("referral_code", models.CharField(default="", max_length=50)),
                ("referral_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(name="users",),
    ]
